// q_sys_reset_bridge_0.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module q_sys_reset_bridge_0 (
		input  wire  in_reset_n,  //  in_reset.reset_n, Reset Input
		output wire  out_reset_n  // out_reset.reset_n, Reset Output
	);

	assign out_reset_n = in_reset_n;

endmodule
