// q_sys_s10_user_rst_clkgate_0.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module q_sys_s10_user_rst_clkgate_0 (
		output wire  ninit_done  // ninit_done.reset
	);

	altera_s10_user_rst_clkgate s10_user_rst_clkgate_0 (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.reset
	);

endmodule
