// q_sys_product_info_0.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module q_sys_product_info_0 (
		input  wire        clk,          //       clock_reset.clk
		input  wire        reset_n,      // clock_reset_reset.reset_n
		input  wire        chipselect_n, //    avalon_slave_0.chipselect_n
		input  wire        read_n,       //                  .read_n
		output wire [31:0] av_data_read, //                  .readdata
		input  wire [1:0]  av_address    //                  .address
	);

	product_info product_info_0 (
		.clk          (clk),          //   input,   width = 1,       clock_reset.clk
		.reset_n      (reset_n),      //   input,   width = 1, clock_reset_reset.reset_n
		.chipselect_n (chipselect_n), //   input,   width = 1,    avalon_slave_0.chipselect_n
		.read_n       (read_n),       //   input,   width = 1,                  .read_n
		.av_data_read (av_data_read), //  output,  width = 32,                  .readdata
		.av_address   (av_address)    //   input,   width = 2,                  .address
	);

endmodule
