package ed_synth_emif_ph2_inst_emif_ph2_phy_arch_fp_610_hoyllai_atom_attr_byte_ctrl;
   localparam bit IS_USED  [0:7]                                                     = '{1,
                                                                                         1,
                                                                                         1,
                                                                                         1,
                                                                                         0,
                                                                                         0,
                                                                                         1,
                                                                                         1};
   localparam [15:0] BASE_ADDRESS  [0:7]                                             = '{16'd256,
                                                                                         16'd257,
                                                                                         16'd258,
                                                                                         16'd259,
                                                                                         16'd0,
                                                                                         16'd0,
                                                                                         16'd262,
                                                                                         16'd263};
   localparam int LFIFO_VALUE  [0:7]                                                 = '{7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0};
   localparam string PIN_RX_COARSE_DELAY  [0:95]                                     = '{"PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0",
                                                                                         "PIN0_RX_COARSE_DELAY_0", "PIN1_RX_COARSE_DELAY_0", "PIN2_RX_COARSE_DELAY_0", "PIN3_RX_COARSE_DELAY_0", "PIN4_RX_COARSE_DELAY_0", "PIN5_RX_COARSE_DELAY_0", "PIN6_RX_COARSE_DELAY_0", "PIN7_RX_COARSE_DELAY_0", "PIN8_RX_COARSE_DELAY_0", "PIN9_RX_COARSE_DELAY_0", "PIN10_RX_COARSE_DELAY_0", "PIN11_RX_COARSE_DELAY_0"};
   localparam int PIN_RX_FINE_DELAY  [0:95]                                          = '{7'd31, 7'd31, 7'd31, 7'd31, 7'd0, 7'd0, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31,
                                                                                         7'd31, 7'd31, 7'd31, 7'd31, 7'd0, 7'd0, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd31, 7'd31, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd31, 7'd31, 7'd31, 7'd31, 7'd0, 7'd0, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31,
                                                                                         7'd31, 7'd31, 7'd31, 7'd31, 7'd0, 7'd0, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31, 7'd31};
   localparam string PIN_TX_COARSE_DELAY  [0:95]                                     = '{"PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0",
                                                                                         "PIN0_TX_COARSE_DELAY_0", "PIN1_TX_COARSE_DELAY_0", "PIN2_TX_COARSE_DELAY_0", "PIN3_TX_COARSE_DELAY_0", "PIN4_TX_COARSE_DELAY_0", "PIN5_TX_COARSE_DELAY_0", "PIN6_TX_COARSE_DELAY_0", "PIN7_TX_COARSE_DELAY_0", "PIN8_TX_COARSE_DELAY_0", "PIN9_TX_COARSE_DELAY_0", "PIN10_TX_COARSE_DELAY_0", "PIN11_TX_COARSE_DELAY_0"};
   localparam int PIN_TX_FINE_DELAY  [0:95]                                          = '{7'd0, 7'd0, 7'd0, 7'd0, 7'd31, 7'd31, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd31, 7'd31, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd31, 7'd31, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd31, 7'd31, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0,
                                                                                         7'd0, 7'd0, 7'd0, 7'd0, 7'd31, 7'd31, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0, 7'd0};
   localparam string PIN_RX_USAGE  [0:95]                                            = '{"PIN0_RX_USAGE_DATA", "PIN1_RX_USAGE_DATA", "PIN2_RX_USAGE_DATA", "PIN3_RX_USAGE_DATA", "PIN4_RX_USAGE_DQS", "PIN5_RX_USAGE_DQS", "PIN6_RX_USAGE_DATA", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_DATA", "PIN9_RX_USAGE_DATA", "PIN10_RX_USAGE_DATA", "PIN11_RX_USAGE_DATA",
                                                                                         "PIN0_RX_USAGE_DATA", "PIN1_RX_USAGE_DATA", "PIN2_RX_USAGE_DATA", "PIN3_RX_USAGE_DATA", "PIN4_RX_USAGE_DQS", "PIN5_RX_USAGE_DQS", "PIN6_RX_USAGE_DATA", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_DATA", "PIN9_RX_USAGE_DATA", "PIN10_RX_USAGE_DATA", "PIN11_RX_USAGE_DATA",
                                                                                         "PIN0_RX_USAGE_GPIO", "PIN1_RX_USAGE_GPIO", "PIN2_RX_USAGE_GPIO", "PIN3_RX_USAGE_GPIO", "PIN4_RX_USAGE_GPIO", "PIN5_RX_USAGE_GPIO", "PIN6_RX_USAGE_GPIO", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_GPIO", "PIN9_RX_USAGE_GPIO", "PIN10_RX_USAGE_GPIO", "PIN11_RX_USAGE_GPIO",
                                                                                         "PIN0_RX_USAGE_GPIO", "PIN1_RX_USAGE_GPIO", "PIN2_RX_USAGE_GPIO", "PIN3_RX_USAGE_GPIO", "PIN4_RX_USAGE_GPIO", "PIN5_RX_USAGE_GPIO", "PIN6_RX_USAGE_GPIO", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_GPIO", "PIN9_RX_USAGE_GPIO", "PIN10_RX_USAGE_GPIO", "PIN11_RX_USAGE_GPIO",
                                                                                         "PIN0_RX_USAGE_GPIO", "PIN1_RX_USAGE_GPIO", "PIN2_RX_USAGE_GPIO", "PIN3_RX_USAGE_GPIO", "PIN4_RX_USAGE_GPIO", "PIN5_RX_USAGE_GPIO", "PIN6_RX_USAGE_GPIO", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_GPIO", "PIN9_RX_USAGE_GPIO", "PIN10_RX_USAGE_GPIO", "PIN11_RX_USAGE_GPIO",
                                                                                         "PIN0_RX_USAGE_GPIO", "PIN1_RX_USAGE_GPIO", "PIN2_RX_USAGE_GPIO", "PIN3_RX_USAGE_GPIO", "PIN4_RX_USAGE_GPIO", "PIN5_RX_USAGE_GPIO", "PIN6_RX_USAGE_GPIO", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_GPIO", "PIN9_RX_USAGE_GPIO", "PIN10_RX_USAGE_GPIO", "PIN11_RX_USAGE_GPIO",
                                                                                         "PIN0_RX_USAGE_DATA", "PIN1_RX_USAGE_DATA", "PIN2_RX_USAGE_DATA", "PIN3_RX_USAGE_DATA", "PIN4_RX_USAGE_DQS", "PIN5_RX_USAGE_DQS", "PIN6_RX_USAGE_DATA", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_DATA", "PIN9_RX_USAGE_DATA", "PIN10_RX_USAGE_DATA", "PIN11_RX_USAGE_DATA",
                                                                                         "PIN0_RX_USAGE_DATA", "PIN1_RX_USAGE_DATA", "PIN2_RX_USAGE_DATA", "PIN3_RX_USAGE_DATA", "PIN4_RX_USAGE_DQS", "PIN5_RX_USAGE_DQS", "PIN6_RX_USAGE_DATA", "PIN7_RX_USAGE_GPIO", "PIN8_RX_USAGE_DATA", "PIN9_RX_USAGE_DATA", "PIN10_RX_USAGE_DATA", "PIN11_RX_USAGE_DATA"};
   localparam string PIN_TX_USAGE  [0:95]                                            = '{"PIN0_TX_USAGE_DATA", "PIN1_TX_USAGE_DATA", "PIN2_TX_USAGE_DATA", "PIN3_TX_USAGE_DATA", "PIN4_TX_USAGE_DQS", "PIN5_TX_USAGE_DQS", "PIN6_TX_USAGE_DATA", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_DATA", "PIN9_TX_USAGE_DATA", "PIN10_TX_USAGE_DATA", "PIN11_TX_USAGE_DATA",
                                                                                         "PIN0_TX_USAGE_DATA", "PIN1_TX_USAGE_DATA", "PIN2_TX_USAGE_DATA", "PIN3_TX_USAGE_DATA", "PIN4_TX_USAGE_DQS", "PIN5_TX_USAGE_DQS", "PIN6_TX_USAGE_DATA", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_DATA", "PIN9_TX_USAGE_DATA", "PIN10_TX_USAGE_DATA", "PIN11_TX_USAGE_DATA",
                                                                                         "PIN0_TX_USAGE_CA", "PIN1_TX_USAGE_CA", "PIN2_TX_USAGE_CA", "PIN3_TX_USAGE_CA", "PIN4_TX_USAGE_CA", "PIN5_TX_USAGE_CA", "PIN6_TX_USAGE_CA", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_CA", "PIN9_TX_USAGE_GPIO", "PIN10_TX_USAGE_GPIO", "PIN11_TX_USAGE_GPIO",
                                                                                         "PIN0_TX_USAGE_GPIO", "PIN1_TX_USAGE_GPIO", "PIN2_TX_USAGE_GPIO", "PIN3_TX_USAGE_CA", "PIN4_TX_USAGE_GPIO", "PIN5_TX_USAGE_GPIO", "PIN6_TX_USAGE_CLK", "PIN7_TX_USAGE_CLK", "PIN8_TX_USAGE_GPIO", "PIN9_TX_USAGE_GPIO", "PIN10_TX_USAGE_GPIO", "PIN11_TX_USAGE_GPIO",
                                                                                         "PIN0_TX_USAGE_GPIO", "PIN1_TX_USAGE_GPIO", "PIN2_TX_USAGE_GPIO", "PIN3_TX_USAGE_GPIO", "PIN4_TX_USAGE_GPIO", "PIN5_TX_USAGE_GPIO", "PIN6_TX_USAGE_GPIO", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_GPIO", "PIN9_TX_USAGE_GPIO", "PIN10_TX_USAGE_GPIO", "PIN11_TX_USAGE_GPIO",
                                                                                         "PIN0_TX_USAGE_GPIO", "PIN1_TX_USAGE_GPIO", "PIN2_TX_USAGE_GPIO", "PIN3_TX_USAGE_GPIO", "PIN4_TX_USAGE_GPIO", "PIN5_TX_USAGE_GPIO", "PIN6_TX_USAGE_GPIO", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_GPIO", "PIN9_TX_USAGE_GPIO", "PIN10_TX_USAGE_GPIO", "PIN11_TX_USAGE_GPIO",
                                                                                         "PIN0_TX_USAGE_DATA", "PIN1_TX_USAGE_DATA", "PIN2_TX_USAGE_DATA", "PIN3_TX_USAGE_DATA", "PIN4_TX_USAGE_DQS", "PIN5_TX_USAGE_DQS", "PIN6_TX_USAGE_DATA", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_DATA", "PIN9_TX_USAGE_DATA", "PIN10_TX_USAGE_DATA", "PIN11_TX_USAGE_DATA",
                                                                                         "PIN0_TX_USAGE_DATA", "PIN1_TX_USAGE_DATA", "PIN2_TX_USAGE_DATA", "PIN3_TX_USAGE_DATA", "PIN4_TX_USAGE_DQS", "PIN5_TX_USAGE_DQS", "PIN6_TX_USAGE_DATA", "PIN7_TX_USAGE_GPIO", "PIN8_TX_USAGE_DATA", "PIN9_TX_USAGE_DATA", "PIN10_TX_USAGE_DATA", "PIN11_TX_USAGE_DATA"};
   localparam string RESET_AUTO_RELEASE  [0:7]                                       = '{"RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE",
                                                                                         "RESET_AUTO_RELEASE_DISABLE"};
   localparam string RX_IO_STANDARD  [0:7]                                           = '{"RX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "RX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "RX_IO_STANDARD_IOSTD_LVDSRX11",
                                                                                         "RX_IO_STANDARD_IOSTD_LVDSRX11",
                                                                                         "RX_IO_STANDARD_IOSTD_OFF",
                                                                                         "RX_IO_STANDARD_IOSTD_OFF",
                                                                                         "RX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "RX_IO_STANDARD_IOSTD_LVSTL11"};
   localparam string RX_BURST_LENGTH  [0:7]                                          = '{"RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16",
                                                                                         "RX_BURST_LENGTH_16"};
   localparam string RX_CLOCK_SOURCE  [0:7]                                          = '{"RX_CLOCK_SOURCE_EXTERNAL_X8",
                                                                                         "RX_CLOCK_SOURCE_EXTERNAL_X8",
                                                                                         "RX_CLOCK_SOURCE_OFF",
                                                                                         "RX_CLOCK_SOURCE_OFF",
                                                                                         "RX_CLOCK_SOURCE_EXTERNAL_X4",
                                                                                         "RX_CLOCK_SOURCE_EXTERNAL_X4",
                                                                                         "RX_CLOCK_SOURCE_EXTERNAL_X8",
                                                                                         "RX_CLOCK_SOURCE_EXTERNAL_X8"};
   localparam string RX_USAGE_MODE  [0:7]                                            = '{"RX_USAGE_MODE_LPDDR4",
                                                                                         "RX_USAGE_MODE_LPDDR4",
                                                                                         "RX_USAGE_MODE_GPIO",
                                                                                         "RX_USAGE_MODE_GPIO",
                                                                                         "RX_USAGE_MODE_UNUSED",
                                                                                         "RX_USAGE_MODE_UNUSED",
                                                                                         "RX_USAGE_MODE_LPDDR4",
                                                                                         "RX_USAGE_MODE_LPDDR4"};
   localparam string RX_SAMPLER_MODE  [0:7]                                          = '{"RX_SAMPLER_MODE_MATCHED_LOW_COMMON_MODE",
                                                                                         "RX_SAMPLER_MODE_MATCHED_LOW_COMMON_MODE",
                                                                                         "RX_SAMPLER_MODE_MATCHED_HIGH_COMMON_MODE",
                                                                                         "RX_SAMPLER_MODE_MATCHED_HIGH_COMMON_MODE",
                                                                                         "RX_SAMPLER_MODE_HIGH_COMMON_DIFFERENTIAL",
                                                                                         "RX_SAMPLER_MODE_HIGH_COMMON_DIFFERENTIAL",
                                                                                         "RX_SAMPLER_MODE_MATCHED_LOW_COMMON_MODE",
                                                                                         "RX_SAMPLER_MODE_MATCHED_LOW_COMMON_MODE"};
   localparam string RX_SELF_CALIBRATION  [0:7]                                      = '{"RX_SELF_CALIBRATION_DISABLED",
                                                                                         "RX_SELF_CALIBRATION_DISABLED",
                                                                                         "RX_SELF_CALIBRATION_DISABLED",
                                                                                         "RX_SELF_CALIBRATION_DISABLED",
                                                                                         "RX_SELF_CALIBRATION_CENTER_ALIGNED",
                                                                                         "RX_SELF_CALIBRATION_CENTER_ALIGNED",
                                                                                         "RX_SELF_CALIBRATION_DISABLED",
                                                                                         "RX_SELF_CALIBRATION_DISABLED"};
   localparam string RX_SERIALIZER_RATE  [0:7]                                       = '{"RX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "RX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "RX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "RX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "RX_SERIALIZER_RATE_BYPASS",
                                                                                         "RX_SERIALIZER_RATE_BYPASS",
                                                                                         "RX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "RX_SERIALIZER_RATE_HALF_RATE"};
   localparam string TX_IO_STANDARD  [0:7]                                           = '{"TX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "TX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "TX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "TX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "TX_IO_STANDARD_IOSTD_OFF",
                                                                                         "TX_IO_STANDARD_IOSTD_OFF",
                                                                                         "TX_IO_STANDARD_IOSTD_LVSTL11",
                                                                                         "TX_IO_STANDARD_IOSTD_LVSTL11"};
   localparam string TX_PREAMBLE  [0:7]                                              = '{"TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF",
                                                                                         "TX_PREAMBLE_OFF"};
   localparam string TX_USAGE_MODE  [0:7]                                            = '{"TX_USAGE_MODE_LPDDR4",
                                                                                         "TX_USAGE_MODE_LPDDR4",
                                                                                         "TX_USAGE_MODE_LPDDR4",
                                                                                         "TX_USAGE_MODE_LPDDR4",
                                                                                         "TX_USAGE_MODE_UNUSED",
                                                                                         "TX_USAGE_MODE_UNUSED",
                                                                                         "TX_USAGE_MODE_LPDDR4",
                                                                                         "TX_USAGE_MODE_LPDDR4"};
   localparam string TX_SERIALIZER_RATE  [0:7]                                       = '{"TX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "TX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "TX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "TX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "TX_SERIALIZER_RATE_BYPASS",
                                                                                         "TX_SERIALIZER_RATE_BYPASS",
                                                                                         "TX_SERIALIZER_RATE_HALF_RATE",
                                                                                         "TX_SERIALIZER_RATE_HALF_RATE"};
   localparam [35:0] VCO_FREQ  [0:7]                                                 = '{36'd933000000,
                                                                                         36'd933000000,
                                                                                         36'd933000000,
                                                                                         36'd933000000,
                                                                                         36'd0,
                                                                                         36'd0,
                                                                                         36'd933000000,
                                                                                         36'd933000000};
   localparam int VFIFO_VALUE  [0:7]                                                 = '{7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0};
   localparam int OUTPUTENABLE_TO_WRFIFO_OFFSET  [0:7]                               = '{3'd0,
                                                                                         3'd0,
                                                                                         3'd0,
                                                                                         3'd0,
                                                                                         3'd0,
                                                                                         3'd0,
                                                                                         3'd0,
                                                                                         3'd0};
   localparam string RCVEN_COARSE_DELAY  [0:7]                                       = '{"RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0",
                                                                                         "RCVEN_COARSE_DELAY_0"};
   localparam int RCVEN_FINE_DELAY  [0:7]                                            = '{7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0,
                                                                                         7'd0};
   localparam int RCVEN_TO_READ_VALID_OFFSET  [0:7]                                  = '{4'd6,
                                                                                         4'd6,
                                                                                         4'd6,
                                                                                         4'd6,
                                                                                         4'd0,
                                                                                         4'd0,
                                                                                         4'd6,
                                                                                         4'd6};
endpackage
