package ed_synth_emif_ph2_inst_emif_ph2_phy_arch_fp_610_hoyllai_atom_attr_pa;
   localparam bit IS_USED  [0:7]                                                     = '{1,
                                                                                         1,
                                                                                         1,
                                                                                         1,
                                                                                         0,
                                                                                         0,
                                                                                         1,
                                                                                         1};
   localparam [15:0] BASE_ADDRESS  [0:7]                                             = '{16'd272,
                                                                                         16'd273,
                                                                                         16'd274,
                                                                                         16'd275,
                                                                                         16'd276,
                                                                                         16'd277,
                                                                                         16'd278,
                                                                                         16'd279};
   localparam string CONTROLLER  [0:7]                                               = '{"CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD",
                                                                                         "CONTROLLER_HARD"};
   localparam string DDR_LANE_MODE  [0:7]                                            = '{"DDR_LANE_MODE_DQ",
                                                                                         "DDR_LANE_MODE_DQ",
                                                                                         "DDR_LANE_MODE_AC",
                                                                                         "DDR_LANE_MODE_AC",
                                                                                         "DDR_LANE_MODE_AC",
                                                                                         "DDR_LANE_MODE_AC",
                                                                                         "DDR_LANE_MODE_DQ",
                                                                                         "DDR_LANE_MODE_DQ"};
   localparam string MIPI_FUNC  [0:7]                                                = '{"MIPI_FUNC_OFF",
                                                                                         "MIPI_FUNC_OFF",
                                                                                         "MIPI_FUNC_OFF",
                                                                                         "MIPI_FUNC_OFF",
                                                                                         "MIPI_FUNC_D1",
                                                                                         "MIPI_FUNC_D1",
                                                                                         "MIPI_FUNC_OFF",
                                                                                         "MIPI_FUNC_OFF"};
   localparam string PIN0_SWIZZLE  [0:7]                                             = '{"PIN0_SWIZZLE_DQ7",
                                                                                         "PIN0_SWIZZLE_DQ0",
                                                                                         "PIN0_SWIZZLE_DQ0",
                                                                                         "PIN0_SWIZZLE_DQ0",
                                                                                         "PIN0_SWIZZLE_DQ0",
                                                                                         "PIN0_SWIZZLE_DQ0",
                                                                                         "PIN0_SWIZZLE_DQ7",
                                                                                         "PIN0_SWIZZLE_DQ3"};
   localparam string PIN1_SWIZZLE  [0:7]                                             = '{"PIN1_SWIZZLE_DQ6",
                                                                                         "PIN1_SWIZZLE_DQ2",
                                                                                         "PIN1_SWIZZLE_DQ1",
                                                                                         "PIN1_SWIZZLE_DQ1",
                                                                                         "PIN1_SWIZZLE_DQ0",
                                                                                         "PIN1_SWIZZLE_DQ0",
                                                                                         "PIN1_SWIZZLE_DQ5",
                                                                                         "PIN1_SWIZZLE_DQ2"};
   localparam string PIN10_SWIZZLE  [0:7]                                            = '{"PIN10_SWIZZLE_DQ2",
                                                                                         "PIN10_SWIZZLE_DQ6",
                                                                                         "PIN10_SWIZZLE_DQ6",
                                                                                         "PIN10_SWIZZLE_DQ6",
                                                                                         "PIN10_SWIZZLE_DQ0",
                                                                                         "PIN10_SWIZZLE_DQ0",
                                                                                         "PIN10_SWIZZLE_DQ2",
                                                                                         "PIN10_SWIZZLE_DQ7"};
   localparam string PIN11_SWIZZLE  [0:7]                                            = '{"PIN11_SWIZZLE_DQ3",
                                                                                         "PIN11_SWIZZLE_DQ5",
                                                                                         "PIN11_SWIZZLE_DQ7",
                                                                                         "PIN11_SWIZZLE_DQ7",
                                                                                         "PIN11_SWIZZLE_DQ0",
                                                                                         "PIN11_SWIZZLE_DQ0",
                                                                                         "PIN11_SWIZZLE_DQ3",
                                                                                         "PIN11_SWIZZLE_DQ6"};
   localparam string PIN2_SWIZZLE  [0:7]                                             = '{"PIN2_SWIZZLE_DQ4",
                                                                                         "PIN2_SWIZZLE_DQ1",
                                                                                         "PIN2_SWIZZLE_DQ2",
                                                                                         "PIN2_SWIZZLE_DQ2",
                                                                                         "PIN2_SWIZZLE_DQ0",
                                                                                         "PIN2_SWIZZLE_DQ0",
                                                                                         "PIN2_SWIZZLE_DQ6",
                                                                                         "PIN2_SWIZZLE_DQ1"};
   localparam string PIN3_SWIZZLE  [0:7]                                             = '{"PIN3_SWIZZLE_DQ5",
                                                                                         "PIN3_SWIZZLE_DQ3",
                                                                                         "PIN3_SWIZZLE_DQ3",
                                                                                         "PIN3_SWIZZLE_DQ3",
                                                                                         "PIN3_SWIZZLE_DQ0",
                                                                                         "PIN3_SWIZZLE_DQ0",
                                                                                         "PIN3_SWIZZLE_DQ4",
                                                                                         "PIN3_SWIZZLE_DQ0"};
   localparam string PIN8_SWIZZLE  [0:7]                                             = '{"PIN8_SWIZZLE_DQ1",
                                                                                         "PIN8_SWIZZLE_DQ7",
                                                                                         "PIN8_SWIZZLE_DQ4",
                                                                                         "PIN8_SWIZZLE_DQ4",
                                                                                         "PIN8_SWIZZLE_DQ0",
                                                                                         "PIN8_SWIZZLE_DQ0",
                                                                                         "PIN8_SWIZZLE_DQ1",
                                                                                         "PIN8_SWIZZLE_DQ5"};
   localparam string PIN9_SWIZZLE  [0:7]                                             = '{"PIN9_SWIZZLE_DQ0",
                                                                                         "PIN9_SWIZZLE_DQ4",
                                                                                         "PIN9_SWIZZLE_DQ5",
                                                                                         "PIN9_SWIZZLE_DQ5",
                                                                                         "PIN9_SWIZZLE_DQ0",
                                                                                         "PIN9_SWIZZLE_DQ0",
                                                                                         "PIN9_SWIZZLE_DQ0",
                                                                                         "PIN9_SWIZZLE_DQ4"};
   localparam string RATE_CONV  [0:7]                                                = '{"RATE_CONV_QR_HR_CONV_EN",
                                                                                         "RATE_CONV_QR_HR_CONV_EN",
                                                                                         "RATE_CONV_QR_HR_CONV_EN",
                                                                                         "RATE_CONV_QR_HR_CONV_EN",
                                                                                         "RATE_CONV_HR_FR_CONV_EN",
                                                                                         "RATE_CONV_HR_FR_CONV_EN",
                                                                                         "RATE_CONV_QR_HR_CONV_EN",
                                                                                         "RATE_CONV_QR_HR_CONV_EN"};
endpackage
