// (C) 2001-2024 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


module ed_synth_emif_ph2_inst_emif_ph2_cal_arch_fp_410_7vxea4y_stdfn_inst_seq #(
   localparam PORT_I_AVL_ADDRESS_WIDTH                        = 22,
   localparam PORT_I_AVL_READDATA_CKGEN_WIDTH                 = 32,
   localparam PORT_I_AVL_READDATA_COMP_WIDTH                  = 32,
   localparam PORT_I_AVL_READDATA_FBRPLL_WIDTH                = 32,
   localparam PORT_I_AVL_READDATA_IOPLL_WIDTH                 = 32,
   localparam PORT_I_AVL_READDATA_LANE_WIDTH                  = 32,
   localparam PORT_I_AVL_WRITEDATA_WIDTH                      = 32,
   localparam PORT_I_RB_BASE_ADDRESS_PA_WIDTH                 = 11,
   localparam PORT_I_SEQ_RDDATA_WIDTH                         = 96,
   localparam PORT_I_SEQ_RDDATA_VALID_WIDTH                   = 4,
   localparam PORT_O_AVL_ADDRESS_CKGEN_WIDTH                  = 22,
   localparam PORT_O_AVL_ADDRESS_COMP_WIDTH                   = 22,
   localparam PORT_O_AVL_ADDRESS_LANE_WIDTH                   = 22,
   localparam PORT_O_AVL_ADDRESS_PLL_WIDTH                    = 22,
   localparam PORT_O_AVL_READDATA_WIDTH                       = 32,
   localparam PORT_O_AVL_WRITEDATA_CKGEN_WIDTH                = 32,
   localparam PORT_O_AVL_WRITEDATA_COMP_WIDTH                 = 32,
   localparam PORT_O_AVL_WRITEDATA_LANE_WIDTH                 = 32,
   localparam PORT_O_AVL_WRITEDATA_PLL_WIDTH                  = 32,
   localparam PORT_O_SEQ_RDDATA_EN_WIDTH                      = 4,
   localparam PORT_O_SEQ_RD_RANK_WIDTH                        = 8,
   localparam PORT_O_SEQ_SUPPRESSION_WIDTH                    = 12,
   localparam PORT_O_SEQ_WRDATA_WIDTH                         = 96,
   localparam PORT_O_SEQ_WRDATA_EN_WIDTH                      = 4,
   localparam PORT_O_SEQ_WR_DQS_EN_WIDTH                      = 4,
   localparam PORT_O_SEQ_WR_RANK_WIDTH                        = 8
) (

   input  [PORT_I_AVL_ADDRESS_WIDTH-1:0]                       i_avl_address,
   input                                                       i_avl_clk,
   input                                                       i_avl_read,
   input  [PORT_I_AVL_READDATA_CKGEN_WIDTH-1:0]                i_avl_readdata_ckgen0,
   input  [PORT_I_AVL_READDATA_CKGEN_WIDTH-1:0]                i_avl_readdata_ckgen1,
   input  [PORT_I_AVL_READDATA_COMP_WIDTH-1:0]                 i_avl_readdata_comp,
   input  [PORT_I_AVL_READDATA_FBRPLL_WIDTH-1:0]               i_avl_readdata_fbrpll,
   input  [PORT_I_AVL_READDATA_IOPLL_WIDTH-1:0]                i_avl_readdata_iopll0,
   input  [PORT_I_AVL_READDATA_IOPLL_WIDTH-1:0]                i_avl_readdata_iopll1,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane0,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane1,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane2,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane3,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane4,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane5,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane6,
   input  [PORT_I_AVL_READDATA_LANE_WIDTH-1:0]                 i_avl_readdata_lane7,
   input                                                       i_avl_rstn,
   input                                                       i_avl_write,
   input  [PORT_I_AVL_WRITEDATA_WIDTH-1:0]                     i_avl_writedata,
   input                                                       i_phy_clka,
   input                                                       i_phy_clkb,
   input                                                       i_phy_clksync_a,
   input                                                       i_phy_clksync_b,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa0,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa1,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa2,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa3,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa4,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa5,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa6,
   input  [PORT_I_RB_BASE_ADDRESS_PA_WIDTH-1:0]                i_rb_base_address_pa7,
   input                                                       i_rb_ddr_lane_mode_pa0,
   input                                                       i_rb_ddr_lane_mode_pa1,
   input                                                       i_rb_ddr_lane_mode_pa2,
   input                                                       i_rb_ddr_lane_mode_pa3,
   input                                                       i_rb_ddr_lane_mode_pa4,
   input                                                       i_rb_ddr_lane_mode_pa5,
   input                                                       i_rb_ddr_lane_mode_pa6,
   input                                                       i_rb_ddr_lane_mode_pa7,
   input                                                       i_rb_if_sel_pa0,
   input                                                       i_rb_if_sel_pa1,
   input                                                       i_rb_if_sel_pa2,
   input                                                       i_rb_if_sel_pa3,
   input                                                       i_rb_if_sel_pa4,
   input                                                       i_rb_if_sel_pa5,
   input                                                       i_rb_if_sel_pa6,
   input                                                       i_rb_if_sel_pa7,
   input                                                       i_rb_phy_clk_en_pa0,
   input                                                       i_rb_phy_clk_en_pa1,
   input                                                       i_rb_phy_clk_en_pa2,
   input                                                       i_rb_phy_clk_en_pa3,
   input                                                       i_rb_phy_clk_en_pa4,
   input                                                       i_rb_phy_clk_en_pa5,
   input                                                       i_rb_phy_clk_en_pa6,
   input                                                       i_rb_phy_clk_en_pa7,
   input                                                       i_rb_rate_conv_en_pa0,
   input                                                       i_rb_rate_conv_en_pa1,
   input                                                       i_rb_rate_conv_en_pa2,
   input                                                       i_rb_rate_conv_en_pa3,
   input                                                       i_rb_rate_conv_en_pa4,
   input                                                       i_rb_rate_conv_en_pa5,
   input                                                       i_rb_rate_conv_en_pa6,
   input                                                       i_rb_rate_conv_en_pa7,
   input                                                       i_seq_cmd_sync,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_0,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_1,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_2,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_3,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_4,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_5,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_6,
   input  [PORT_I_SEQ_RDDATA_WIDTH-1:0]                        i_seq_rddata_7,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_0,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_1,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_2,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_3,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_4,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_5,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_6,
   input  [PORT_I_SEQ_RDDATA_VALID_WIDTH-1:0]                  i_seq_rddata_valid_7,
   output [PORT_O_AVL_ADDRESS_CKGEN_WIDTH-1:0]                 o_avl_address_ckgen,
   output [PORT_O_AVL_ADDRESS_COMP_WIDTH-1:0]                  o_avl_address_comp,
   output [PORT_O_AVL_ADDRESS_LANE_WIDTH-1:0]                  o_avl_address_lane,
   output [PORT_O_AVL_ADDRESS_PLL_WIDTH-1:0]                   o_avl_address_pll,
   output                                                      o_avl_clk_ckgen,
   output                                                      o_avl_clk_comp,
   output                                                      o_avl_clk_lane,
   output                                                      o_avl_clk_pll,
   output [PORT_O_AVL_READDATA_WIDTH-1:0]                      o_avl_readdata,
   output                                                      o_avl_read_ckgen,
   output                                                      o_avl_read_comp,
   output                                                      o_avl_read_lane,
   output                                                      o_avl_read_pll,
   output                                                      o_avl_rstn_ckgen,
   output                                                      o_avl_rstn_comp,
   output                                                      o_avl_rstn_lane,
   output                                                      o_avl_rstn_pll,
   output [PORT_O_AVL_WRITEDATA_CKGEN_WIDTH-1:0]               o_avl_writedata_ckgen,
   output [PORT_O_AVL_WRITEDATA_COMP_WIDTH-1:0]                o_avl_writedata_comp,
   output [PORT_O_AVL_WRITEDATA_LANE_WIDTH-1:0]                o_avl_writedata_lane,
   output [PORT_O_AVL_WRITEDATA_PLL_WIDTH-1:0]                 o_avl_writedata_pll,
   output                                                      o_avl_write_ckgen,
   output                                                      o_avl_write_comp,
   output                                                      o_avl_write_lane,
   output                                                      o_avl_write_pll,
   output                                                      o_seq_cmd_sync,
   output                                                      o_seq_en_0,
   output                                                      o_seq_en_1,
   output                                                      o_seq_en_2,
   output                                                      o_seq_en_3,
   output                                                      o_seq_en_4,
   output                                                      o_seq_en_5,
   output                                                      o_seq_en_6,
   output                                                      o_seq_en_7,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_0,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_1,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_2,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_3,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_4,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_5,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_6,
   output [PORT_O_SEQ_RDDATA_EN_WIDTH-1:0]                     o_seq_rddata_en_7,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_0,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_1,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_2,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_3,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_4,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_5,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_6,
   output [PORT_O_SEQ_RD_RANK_WIDTH-1:0]                       o_seq_rd_rank_7,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_0,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_1,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_2,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_3,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_4,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_5,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_6,
   output [PORT_O_SEQ_SUPPRESSION_WIDTH-1:0]                   o_seq_suppression_7,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_0,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_1,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_2,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_3,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_4,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_5,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_6,
   output [PORT_O_SEQ_WRDATA_EN_WIDTH-1:0]                     o_seq_wrdata_en_7,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_0,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_1,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_2,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_3,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_4,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_5,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_6,
   output [PORT_O_SEQ_WRDATA_WIDTH-1:0]                        o_seq_wrdata_7,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_0,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_1,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_2,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_3,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_4,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_5,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_6,
   output [PORT_O_SEQ_WR_DQS_EN_WIDTH-1:0]                     o_seq_wr_dqs_en_7,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_0,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_1,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_2,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_3,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_4,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_5,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_6,
   output [PORT_O_SEQ_WR_RANK_WIDTH-1:0]                       o_seq_wr_rank_7

);
   timeunit 1ns;
   timeprecision 1ps;
   import ed_synth_emif_ph2_inst_emif_ph2_cal_arch_fp_410_7vxea4y_atom_attr_seq::*;

   tennm_seq # (
      .base_address_ctrl                                    (BASE_ADDRESS_CTRL)
   ) seq (
      .i_avl_address                                        (i_avl_address),
      .i_avl_clk                                            (i_avl_clk),
      .i_avl_read                                           (i_avl_read),
      .i_avl_readdata_ckgen0                                (i_avl_readdata_ckgen0),
      .i_avl_readdata_ckgen1                                (i_avl_readdata_ckgen1),
      .i_avl_readdata_comp                                  (i_avl_readdata_comp),
      .i_avl_readdata_fbrpll                                (i_avl_readdata_fbrpll),
      .i_avl_readdata_iopll0                                (i_avl_readdata_iopll0),
      .i_avl_readdata_iopll1                                (i_avl_readdata_iopll1),
      .i_avl_readdata_lane0                                 (i_avl_readdata_lane0),
      .i_avl_readdata_lane1                                 (i_avl_readdata_lane1),
      .i_avl_readdata_lane2                                 (i_avl_readdata_lane2),
      .i_avl_readdata_lane3                                 (i_avl_readdata_lane3),
      .i_avl_readdata_lane4                                 (i_avl_readdata_lane4),
      .i_avl_readdata_lane5                                 (i_avl_readdata_lane5),
      .i_avl_readdata_lane6                                 (i_avl_readdata_lane6),
      .i_avl_readdata_lane7                                 (i_avl_readdata_lane7),
      .i_avl_rstn                                           (i_avl_rstn),
      .i_avl_write                                          (i_avl_write),
      .i_avl_writedata                                      (i_avl_writedata),
      .i_phy_clka                                           (i_phy_clka),
      .i_phy_clkb                                           (i_phy_clkb),
      .i_phy_clksync_a                                      (i_phy_clksync_a),
      .i_phy_clksync_b                                      (i_phy_clksync_b),
      .i_rb_base_address_pa0                                (i_rb_base_address_pa0),
      .i_rb_base_address_pa1                                (i_rb_base_address_pa1),
      .i_rb_base_address_pa2                                (i_rb_base_address_pa2),
      .i_rb_base_address_pa3                                (i_rb_base_address_pa3),
      .i_rb_base_address_pa4                                (i_rb_base_address_pa4),
      .i_rb_base_address_pa5                                (i_rb_base_address_pa5),
      .i_rb_base_address_pa6                                (i_rb_base_address_pa6),
      .i_rb_base_address_pa7                                (i_rb_base_address_pa7),
      .i_rb_ddr_lane_mode_pa0                               (i_rb_ddr_lane_mode_pa0),
      .i_rb_ddr_lane_mode_pa1                               (i_rb_ddr_lane_mode_pa1),
      .i_rb_ddr_lane_mode_pa2                               (i_rb_ddr_lane_mode_pa2),
      .i_rb_ddr_lane_mode_pa3                               (i_rb_ddr_lane_mode_pa3),
      .i_rb_ddr_lane_mode_pa4                               (i_rb_ddr_lane_mode_pa4),
      .i_rb_ddr_lane_mode_pa5                               (i_rb_ddr_lane_mode_pa5),
      .i_rb_ddr_lane_mode_pa6                               (i_rb_ddr_lane_mode_pa6),
      .i_rb_ddr_lane_mode_pa7                               (i_rb_ddr_lane_mode_pa7),
      .i_rb_if_sel_pa0                                      (i_rb_if_sel_pa0),
      .i_rb_if_sel_pa1                                      (i_rb_if_sel_pa1),
      .i_rb_if_sel_pa2                                      (i_rb_if_sel_pa2),
      .i_rb_if_sel_pa3                                      (i_rb_if_sel_pa3),
      .i_rb_if_sel_pa4                                      (i_rb_if_sel_pa4),
      .i_rb_if_sel_pa5                                      (i_rb_if_sel_pa5),
      .i_rb_if_sel_pa6                                      (i_rb_if_sel_pa6),
      .i_rb_if_sel_pa7                                      (i_rb_if_sel_pa7),
      .i_rb_phy_clk_en_pa0                                  (i_rb_phy_clk_en_pa0),
      .i_rb_phy_clk_en_pa1                                  (i_rb_phy_clk_en_pa1),
      .i_rb_phy_clk_en_pa2                                  (i_rb_phy_clk_en_pa2),
      .i_rb_phy_clk_en_pa3                                  (i_rb_phy_clk_en_pa3),
      .i_rb_phy_clk_en_pa4                                  (i_rb_phy_clk_en_pa4),
      .i_rb_phy_clk_en_pa5                                  (i_rb_phy_clk_en_pa5),
      .i_rb_phy_clk_en_pa6                                  (i_rb_phy_clk_en_pa6),
      .i_rb_phy_clk_en_pa7                                  (i_rb_phy_clk_en_pa7),
      .i_rb_rate_conv_en_pa0                                (i_rb_rate_conv_en_pa0),
      .i_rb_rate_conv_en_pa1                                (i_rb_rate_conv_en_pa1),
      .i_rb_rate_conv_en_pa2                                (i_rb_rate_conv_en_pa2),
      .i_rb_rate_conv_en_pa3                                (i_rb_rate_conv_en_pa3),
      .i_rb_rate_conv_en_pa4                                (i_rb_rate_conv_en_pa4),
      .i_rb_rate_conv_en_pa5                                (i_rb_rate_conv_en_pa5),
      .i_rb_rate_conv_en_pa6                                (i_rb_rate_conv_en_pa6),
      .i_rb_rate_conv_en_pa7                                (i_rb_rate_conv_en_pa7),
      .i_seq_cmd_sync                                       (i_seq_cmd_sync),
      .i_seq_rddata_0                                       (i_seq_rddata_0),
      .i_seq_rddata_1                                       (i_seq_rddata_1),
      .i_seq_rddata_2                                       (i_seq_rddata_2),
      .i_seq_rddata_3                                       (i_seq_rddata_3),
      .i_seq_rddata_4                                       (i_seq_rddata_4),
      .i_seq_rddata_5                                       (i_seq_rddata_5),
      .i_seq_rddata_6                                       (i_seq_rddata_6),
      .i_seq_rddata_7                                       (i_seq_rddata_7),
      .i_seq_rddata_valid_0                                 (i_seq_rddata_valid_0),
      .i_seq_rddata_valid_1                                 (i_seq_rddata_valid_1),
      .i_seq_rddata_valid_2                                 (i_seq_rddata_valid_2),
      .i_seq_rddata_valid_3                                 (i_seq_rddata_valid_3),
      .i_seq_rddata_valid_4                                 (i_seq_rddata_valid_4),
      .i_seq_rddata_valid_5                                 (i_seq_rddata_valid_5),
      .i_seq_rddata_valid_6                                 (i_seq_rddata_valid_6),
      .i_seq_rddata_valid_7                                 (i_seq_rddata_valid_7),
      .o_avl_address_ckgen                                  (o_avl_address_ckgen),
      .o_avl_address_comp                                   (o_avl_address_comp),
      .o_avl_address_lane                                   (o_avl_address_lane),
      .o_avl_address_pll                                    (o_avl_address_pll),
      .o_avl_clk_ckgen                                      (o_avl_clk_ckgen),
      .o_avl_clk_comp                                       (o_avl_clk_comp),
      .o_avl_clk_lane                                       (o_avl_clk_lane),
      .o_avl_clk_pll                                        (o_avl_clk_pll),
      .o_avl_readdata                                       (o_avl_readdata),
      .o_avl_read_ckgen                                     (o_avl_read_ckgen),
      .o_avl_read_comp                                      (o_avl_read_comp),
      .o_avl_read_lane                                      (o_avl_read_lane),
      .o_avl_read_pll                                       (o_avl_read_pll),
      .o_avl_rstn_ckgen                                     (o_avl_rstn_ckgen),
      .o_avl_rstn_comp                                      (o_avl_rstn_comp),
      .o_avl_rstn_lane                                      (o_avl_rstn_lane),
      .o_avl_rstn_pll                                       (o_avl_rstn_pll),
      .o_avl_writedata_ckgen                                (o_avl_writedata_ckgen),
      .o_avl_writedata_comp                                 (o_avl_writedata_comp),
      .o_avl_writedata_lane                                 (o_avl_writedata_lane),
      .o_avl_writedata_pll                                  (o_avl_writedata_pll),
      .o_avl_write_ckgen                                    (o_avl_write_ckgen),
      .o_avl_write_comp                                     (o_avl_write_comp),
      .o_avl_write_lane                                     (o_avl_write_lane),
      .o_avl_write_pll                                      (o_avl_write_pll),
      .o_seq_cmd_sync                                       (o_seq_cmd_sync),
      .o_seq_en_0                                           (o_seq_en_0),
      .o_seq_en_1                                           (o_seq_en_1),
      .o_seq_en_2                                           (o_seq_en_2),
      .o_seq_en_3                                           (o_seq_en_3),
      .o_seq_en_4                                           (o_seq_en_4),
      .o_seq_en_5                                           (o_seq_en_5),
      .o_seq_en_6                                           (o_seq_en_6),
      .o_seq_en_7                                           (o_seq_en_7),
      .o_seq_rddata_en_0                                    (o_seq_rddata_en_0),
      .o_seq_rddata_en_1                                    (o_seq_rddata_en_1),
      .o_seq_rddata_en_2                                    (o_seq_rddata_en_2),
      .o_seq_rddata_en_3                                    (o_seq_rddata_en_3),
      .o_seq_rddata_en_4                                    (o_seq_rddata_en_4),
      .o_seq_rddata_en_5                                    (o_seq_rddata_en_5),
      .o_seq_rddata_en_6                                    (o_seq_rddata_en_6),
      .o_seq_rddata_en_7                                    (o_seq_rddata_en_7),
      .o_seq_rd_rank_0                                      (o_seq_rd_rank_0),
      .o_seq_rd_rank_1                                      (o_seq_rd_rank_1),
      .o_seq_rd_rank_2                                      (o_seq_rd_rank_2),
      .o_seq_rd_rank_3                                      (o_seq_rd_rank_3),
      .o_seq_rd_rank_4                                      (o_seq_rd_rank_4),
      .o_seq_rd_rank_5                                      (o_seq_rd_rank_5),
      .o_seq_rd_rank_6                                      (o_seq_rd_rank_6),
      .o_seq_rd_rank_7                                      (o_seq_rd_rank_7),
      .o_seq_suppression_0                                  (o_seq_suppression_0),
      .o_seq_suppression_1                                  (o_seq_suppression_1),
      .o_seq_suppression_2                                  (o_seq_suppression_2),
      .o_seq_suppression_3                                  (o_seq_suppression_3),
      .o_seq_suppression_4                                  (o_seq_suppression_4),
      .o_seq_suppression_5                                  (o_seq_suppression_5),
      .o_seq_suppression_6                                  (o_seq_suppression_6),
      .o_seq_suppression_7                                  (o_seq_suppression_7),
      .o_seq_wrdata_0                                       (o_seq_wrdata_0),
      .o_seq_wrdata_1                                       (o_seq_wrdata_1),
      .o_seq_wrdata_2                                       (o_seq_wrdata_2),
      .o_seq_wrdata_3                                       (o_seq_wrdata_3),
      .o_seq_wrdata_4                                       (o_seq_wrdata_4),
      .o_seq_wrdata_5                                       (o_seq_wrdata_5),
      .o_seq_wrdata_6                                       (o_seq_wrdata_6),
      .o_seq_wrdata_7                                       (o_seq_wrdata_7),
      .o_seq_wrdata_en_0                                    (o_seq_wrdata_en_0),
      .o_seq_wrdata_en_1                                    (o_seq_wrdata_en_1),
      .o_seq_wrdata_en_2                                    (o_seq_wrdata_en_2),
      .o_seq_wrdata_en_3                                    (o_seq_wrdata_en_3),
      .o_seq_wrdata_en_4                                    (o_seq_wrdata_en_4),
      .o_seq_wrdata_en_5                                    (o_seq_wrdata_en_5),
      .o_seq_wrdata_en_6                                    (o_seq_wrdata_en_6),
      .o_seq_wrdata_en_7                                    (o_seq_wrdata_en_7),
      .o_seq_wr_dqs_en_0                                    (o_seq_wr_dqs_en_0),
      .o_seq_wr_dqs_en_1                                    (o_seq_wr_dqs_en_1),
      .o_seq_wr_dqs_en_2                                    (o_seq_wr_dqs_en_2),
      .o_seq_wr_dqs_en_3                                    (o_seq_wr_dqs_en_3),
      .o_seq_wr_dqs_en_4                                    (o_seq_wr_dqs_en_4),
      .o_seq_wr_dqs_en_5                                    (o_seq_wr_dqs_en_5),
      .o_seq_wr_dqs_en_6                                    (o_seq_wr_dqs_en_6),
      .o_seq_wr_dqs_en_7                                    (o_seq_wr_dqs_en_7),
      .o_seq_wr_rank_0                                      (o_seq_wr_rank_0),
      .o_seq_wr_rank_1                                      (o_seq_wr_rank_1),
      .o_seq_wr_rank_2                                      (o_seq_wr_rank_2),
      .o_seq_wr_rank_3                                      (o_seq_wr_rank_3),
      .o_seq_wr_rank_4                                      (o_seq_wr_rank_4),
      .o_seq_wr_rank_5                                      (o_seq_wr_rank_5),
      .o_seq_wr_rank_6                                      (o_seq_wr_rank_6),
      .o_seq_wr_rank_7                                      (o_seq_wr_rank_7)
   );

endmodule



